package com.codewithola.tradelynkapi.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * ProductImage Entity - Manages multiple images for each product
 * Supports ordering, alt text, and primary image selection
 */
@Entity
@Table(name = "product_images", indexes = {
        @Index(name = "idx_item_id", columnList = "item_id"),
        @Index(name = "idx_position", columnList = "position"),
        @Index(name = "idx_is_primary", columnList = "is_primary")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductImage {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Parent item/product
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "item_id", nullable = false)
    @JsonIgnore
    @ToString.Exclude
    private Item item;

    /**
     * Image URL (Cloudinary)
     */
    @Column(nullable = false, length = 500)
    private String imageUrl;

    /**
     * Thumbnail URL (optimized smaller version)
     * Generated by Cloudinary transformations
     */
    @Column(length = 500)
    private String thumbnailUrl;

    /**
     * Alt text for SEO and accessibility
     */
    @Column(length = 200)
    private String altText;

    /**
     * Position/order for display (lower numbers appear first)
     * 0 = first image, 1 = second, etc.
     */
    @Column(nullable = false)
    @Builder.Default
    private Integer position = 0;

    /**
     * Is this the primary/featured image?
     * Only one image should be primary per product
     */
    @Column(nullable = false)
    @Builder.Default
    private Boolean isPrimary = false;

    /**
     * Width in pixels
     */
    @Column
    private Integer width;

    /**
     * Height in pixels
     */
    @Column
    private Integer height;

    /**
     * File size in bytes
     */
    @Column
    private Long fileSize;

    /**
     * Cloudinary public ID (for deletion/transformation)
     */
    @Column(length = 255)
    private String cloudinaryPublicId;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // ============================================
    // HELPER METHODS
    // ============================================

    /**
     * Generate optimized URL with Cloudinary transformations
     * Example: Resize to 800x800, quality 80, format auto
     */
    public String getOptimizedUrl(int width, int height, int quality) {
        if (imageUrl == null) return null;

        // Example transformation: https://res.cloudinary.com/demo/image/upload/w_800,h_800,c_fill,q_80,f_auto/sample.jpg
        if (imageUrl.contains("cloudinary.com") && imageUrl.contains("/upload/")) {
            String transformation = String.format("w_%d,h_%d,c_fill,q_%d,f_auto/", width, height, quality);
            return imageUrl.replace("/upload/", "/upload/" + transformation);
        }

        return imageUrl;
    }

    /**
     * Get thumbnail (300x300, quality 70)
     */
    public String getThumbnail() {
        if (thumbnailUrl != null) return thumbnailUrl;
        return getOptimizedUrl(300, 300, 70);
    }

    /**
     * Get medium size (800x800, quality 80)
     */
    public String getMediumUrl() {
        return getOptimizedUrl(800, 800, 80);
    }

    /**
     * Get large size (1200x1200, quality 85)
     */
    public String getLargeUrl() {
        return getOptimizedUrl(1200, 1200, 85);
    }
}